[SDK-2671] BrowserStack integration
auth0/lock pull request #2018
Opened 2021-08-06 14:35 UTC by stevehobbsdev

This PR adds BrowserStack support for running E2E tests.

Summary of key changes:

* Replace Mochify, Zuul and Saucelabs with Karma, Browserify and BrowserStack
* Rename NPM test scripts so that they make more sense
* Updated development readme

2021-08-12 15:39 UTC, frederikprijck requested changes

2021-08-12 15:39 UTC, frederikprijck commented on test/enterprise_quick_auth.ui.test.js
> +      );
Let's check if we can solve this without a timeout

2021-08-12 15:39 UTC, frederikprijck commented on test/layout.ui.test.js
> +      }, 1000);
Can we see if we can solve this without timeout

2021-08-12 15:39 UTC, frederikprijck commented on test/social_login.test.js
> +    }, 500);
Can we solve this without a timeout?

2021-08-13 16:04 UTC, stevehobbsdev commented
@frederikprijck I've addressed the comments, I've also moved the BrowserStack tests into their own job.

2021-08-16 09:48 UTC, frederikprijck approved these changes

2021-08-16 09:48 UTC, merged