[IAMRISK-3553] Swapped CAPTCHA on each reload
auth0/lock pull request #2558
Opened 2024-05-23 22:34 UTC by Treterten

### Changes

Updates swap code so that CAPTCHA gets swapped along with the form

### References

[Ticket 1](https://auth0team.atlassian.net/browse/IAMRISK-3552?atlOrigin=eyJpIjoiMzhkOTE3NTNhODkwNDY1N2I5Y2ViMDRlZDE2NjE3OTIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
[Ticket 2](https://auth0team.atlassian.net/browse/IAMRISK-3553?atlOrigin=eyJpIjoiZmYyMjFhYzhkMTZhNGQ4N2ExODk5YWRkMGE4YjA5MTMiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)

### Testing

This can be tested via layer0 by pulling down the changes and running through the instructions under `DEVELOPMENT.md` for `Testing Lock locally through the Universal Login Page`

* [ ] This change adds unit test coverage N/A
* [ ] This change adds integration test coverage N/A 
* [x] This change has been tested on the latest version of the platform/language

### Checklist

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [x] All code quality tools/guidelines have been run/followed
* [x] All relevant assets have been compiled

### Video of Fix

https://github.com/auth0/lock/assets/60672637/24cc1eb6-fe57-4df6-b984-7d35dec558de

2024-05-28 06:32 UTC, nandan-bhat commented
Hi @Treterten,

Can you add some tests for the changes made ? `codecov` checks aren't passing.

2024-05-30 11:58 UTC, frederikprijck requested changes

2024-05-30 11:58 UTC, frederikprijck commented on package.json
> +  "version": "12.5.1",
Can we revert this please? We do not bump versions in feature PRs.

2024-05-30 11:58 UTC, frederikprijck commented on package-lock.json
> +  "version": "12.5.1",
Can we revert this please? We do not bump versions in feature PRs.

2024-05-30 11:58 UTC, frederikprijck commented on package-lock.json
> +      "version": "12.5.1",
Can we revert this please? We do not bump versions in feature PRs.

2024-05-30 12:00 UTC, nandan-bhat requested changes
Please reverse the version-up change. We

2024-05-31 05:18 UTC, nandan-bhat commented
Closing this pull request because [another pull request](https://github.com/auth0/lock/pull/2560) containing the same changes has been merged into the master branch.

2024-05-31 05:18 UTC, nandan-bhat commented
Closing this pull request because [another pull request](https://github.com/auth0/lock/pull/2560) containing the same changes has been merged into the master branch.

2024-05-31 05:18 UTC, closed without merging